# Generated by Django 5.2.8 on 2025-11-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sushi_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="sushi",
            options={"ordering": ["id"]},
        ),
    ]
