# Generated by Django 5.2.8 on 2025-11-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sushi_api", "0002_alter_customer_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sushi_api.customer"
            ),
        ),
    ]
