# Generated by Django 5.2.8 on 2026-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sushi_api", "0003_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
